### ISSUE TITLE
[Feature]: Light Mode and Dark mode 

### ISSUE THREAD

**Issue by Manish5121** [anurrags/Simon-game#1]
I've been testing the project for a while and i don't found any issue with it.
But i think a light theme and dark theme would be a great freature 
i would love to try implementing this feature into this project under hacktoberfest

**Comment by anurrags** [comment]
Yes @Manish5121 you can work on this

**Comment by Rishabh044** [comment]
@anurrags Can multiple people work on the same issue?? Is so I would like to work on the following issue.

**Comment by anurrags** [comment]
@Rishabh044 yes you can work on this issue as well, whoever will solve the issue first or better will get their PR merged.

**Comment by Manish5121** [comment]
hey @anurrags 
i've made this changes in design also i corrected the alignment of rule container a little
lmk about these changes so i can make a pr
- **dark mode** 
![2022-10-03 (1)](https://user-images.githubusercontent.com/94914243/193584959-5d284f38-a911-4b19-99b5-6580210e21da.png)
- **light mode** 
![2022-10-03](https://user-images.githubusercontent.com/94914243/193585014-7727fd8f-c54e-4a11-99d0-3dd7e8677745.png)

**Comment by anurrags** [comment]
@Manish5121  Your repository is 15 commits behind so, i can't check all the functionalities. So please sync your repo with the main repo.

**Comment by Manish5121** [comment]
@anurrags  do i have to clone this repo one more time after sync ?.

should i commit changes before syncing

**Comment by anurrags** [comment]
@Manish5121 Use git upstream as mentioned in contributing.md file. As you have synced the repo, you have to once more commit the changes to your repo and then make a PR

**Comment by Manish5121** [comment]
Thanks for helping submitted my pr
