### ISSUE TITLE
The Font Style Is Not Attractive.

### ISSUE THREAD

**Issue by KiranAminPanjwani** [anurrags/Simon-game#11]
I think that the font style is not very attractive. I would like to change the font family/font style of the text. 
I am a Hacktoberfest participant, please assign this issue to me. Thank you😊

![image](https://user-images.githubusercontent.com/90326051/193466789-dacc6dae-49ca-465e-b9f9-1561cc0bca6b.png)

![image](https://user-images.githubusercontent.com/90326051/193466809-619cc5c6-47ac-4c7b-8fdf-038e3662be73.png)

**Comment by anurrags** [comment]
@KiranAminPanjwani Sorry, but this font-style is fine, you can search for some other issues.
