### ISSUE TITLE
Storing the Highest Score, not reset everytime

### ISSUE THREAD

**Issue by RhyshaKachari** [anurrags/Simon-game#13]
Objectives:
-> Store the Highest Score in Local Storage
-> Render the Highest Score from Local Storage everytime the game starts
-> Enhancing the Game Experience.

**Comment by RhyshaKachari** [comment]
Kindly assign this Issue to me !

**Comment by anurrags** [comment]
@RhyshaKachari Ok you can work on this, i am assigning you
