### ISSUE TITLE
[Bug] : Make background inactive

### ISSUE THREAD

**Issue by anurrags** [anurrags/Simon-game#5]
When rules dialogue box is opened, then buttons beneath it which are visible are clickable. 
Change this to make them inaccessible or not clickable when rules dialogue box opens.

**Comment by Trigstur** [comment]
Could I be assigned?

**Comment by anurrags** [comment]
@Trigstur yes you can start working

**Comment by Trigstur** [comment]
Issue should've been resolved : #7

**Comment by Trigstur** [comment]
Disregard the message above

**Comment by Trigstur** [comment]
Alright #8 should be valid and working
