### ISSUE TITLE
[Enhancement]: Make game responsive for smaller screen sizes

### ISSUE THREAD

**Issue by anurrags** [anurrags/Simon-game#6]
Make the webpage of game responsive for mobiles and tablets

**Comment by Skysparko** [comment]
can i work on it?

**Comment by anurrags** [comment]
@Skysparko yes you can start working on this issue

**Comment by thisShouldNotBeWorking** [comment]
Can I work on this issue as  well?

**Comment by anurrags** [comment]
@con-artist yes you can also work on this.
I am assigning you too in this issue.

**Comment by anurrags** [comment]
Whoever wants to work on this issue, should make sure:
1. Sync your project with the main repository
2. Desktop view should not be changed.
3. In vertical view of mobile and tablet all the content be in middle of the screen.
4. Horizontal tablet view should look same as desktop view, just size of contents adjusted to the screen size.
5. No scroll bar should be required to access any part of the content(except rules dialogue box), that means content should fit the screen.
